### ISSUE TITLE
fwdc handler with variable in name does not work

### ISSUE THREAD

**Issue by RupertAmann** [Flowm/piot-ansible#1]
TASK [fwdc : Copy fwdc service] ****************************************************************************************
ERROR! The requested handler 'Enable fwdc service' was not found in either the main handlers list nor in the listening handlers list

task:
```
- name: Copy fwdc service
  template:
    src: "fwdc.service.j2"
    dest: "/etc/systemd/system/{{ fwdc_service_name }}.service"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - Enable fwdc service
```

Handler:
```
---
- name: "Enable {{ fwdc_service_name }} service"
  systemd:
    name: "{{ fwdc_service_name }}"
    enabled: yes
    state: restarted
    daemon_reload: yes
```

The handler variable needs to be included, but this still won't work (https://github.com/ansible/ansible/issues/24194).
Why using the variable in the task name, shouldn't it be enough to have it in the systemd part?
